orbs:
  slack: circleci/slack@4.4.2
  node: circleci/node@4.5.1
  shellcheck: circleci/shellcheck@2.2.4
  docker: circleci/docker@1.6.0
version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:14.17.3
      - image: circleci/postgres:10.17
        environment:
          POSTGRES_PASSWORD: 5ecr3t
    steps:
      - checkout
      - node/install-packages
      - run: mkdir -p ~/reports/jest
      - run:
          name: Run tests
          command: JEST_JUNIT_OUTPUT_DIR=$HOME/reports/jest npm test -- --reporters=default --reporters=jest-junit
      - run: ./node_modules/.bin/codecov
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
  build:
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run: docker-compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml build --no-cache discounts
  eslint:
    docker:
      - image: cimg/node:14.17.3
    steps:
      - checkout
      - node/install-packages
      - run: mkdir -p ~/reports
      - run: npm run lint -- --format junit --output-file ~/reports/eslint.xml
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
  yamllint:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - checkout
      - run: pip install yamllint
      - run: yamllint -d .yamllint.yml .
  shellcheck:
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      - shellcheck/install
      - shellcheck/check
  audit:
    docker:
      - image: cimg/node:14.17.3
    steps:
      - checkout
      - run: npm audit --production
      - slack/notify:
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "The audit check for `$CIRCLE_PROJECT_REPONAME` has failed."
                  }
                }
              ]
            }
  docker-build-and-push:
    docker:
      - image: cimg/node:14.17.3
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - node/install-packages
      - run: npx semantic-release
      - run: echo $(node -p "require('./package.json').version") >> "$PACKAGE_VERSION"
      - run: docker build  --tag aegee/discounts:$PACKAGE_VERSION --tag aegee/discounts:latest -f docker/discounts/Dockerfile .
      - run: docker login --username $DOCKER_LOGIN --password $DOCKER_PASSWORD
      - run: docker push aegee/discounts:$PACKAGE_VERSION
      - run: docker push aegee/discounts:latest
      - slack/notify:
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "The Docker image for `$CIRCLE_PROJECT_REPONAME` with tags `$PACKAGE_VERSION` and `latest` has been pushed to Dockerhub."
                  }
                }
              ]
            }
      - slack/notify:
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "The Docker image for `$CIRCLE_PROJECT_REPONAME` build and push has failed."
                  }
                }
              ]
            }

workflows:
  version: 2
  linters:
    jobs:
      - eslint
      - yamllint
      - shellcheck
      - docker/hadolint:
          dockerfiles: $(find . -name '*Dockerfile*')
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
  test:
    jobs:
      - test
  docker-build-and-push:
    jobs:
      - docker-build-and-push
      # - docker-build-and-push:
      #     filters:
      #       branches:
      #         only: master
  audit:
    triggers:
      - schedule:
          cron: "0 0 * * 5"
          filters:
            branches:
              only: master
    jobs:
      - audit
