version: "3.4"

services:
  oms-discounts:
    build:
      context: ./${PATH_OMS_DISCOUNTS}/..
      dockerfile: ./docker/oms-discounts/Dockerfile
    image: aegee/oms-discounts:dev
    volumes:
      - ./${PATH_OMS_DISCOUNTS}/../config:/usr/app/src/config
      - ./${PATH_OMS_DISCOUNTS}/../lib:/usr/app/src/lib
      - ./${PATH_OMS_DISCOUNTS}/../migrations:/usr/app/src/migrations
      - ./${PATH_OMS_DISCOUNTS}/../models:/usr/app/src/models
      - ./${PATH_OMS_DISCOUNTS}/../cli.js:/usr/app/src/cli.js
    command: "sh -c '/usr/app/scripts/bootstrap.sh && npm run nodemon-start'"
