version: '3.2'
### OMS DISCOUNTS     #######################################
services:
    postgres-oms-discounts:
        image: postgres:10
        volumes:
            - postgres:/var/lib/postgresql/data
        expose:
            - "5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${PW_POSTGRES}
    oms-discounts:
        build:
            context: ./$PATH_OMS_DISCOUNTS/..
            dockerfile: ./docker/oms-discounts/Dockerfile
        image: aegee/oms-discounts:dev
        volumes:
            - oms-discounts-media:/usr/app/media
            - ./$PATH_OMS_DISCOUNTS/../:/usr/app/src
            - shared:/usr/app/shared:ro
        links:
            - postgres-oms-discounts
        expose:
            - "8084"
        environment:
            BUGSNAG_KEY: bbef84ab99c91665262f672ba6507a2d
        secrets:
            - mail_user
            - mail_password
        labels:
            - "traefik.backend=oms-discounts"
            - "traefik.port=8084"
            - "traefik.frontend.rule=PathPrefix:/services/oms-discounts/api;PathPrefixStrip:/services/oms-discounts/api"
            - "traefik.frontend.priority=110"
            - "traefik.enable=true"

volumes:
    postgres:
        driver: "local"
    oms-discounts-media:
        driver: "local"
    shared:
        driver: "local"

networks:
  default:
    external:
      name: OMS
