version: "3.4"

services:
  oms-discounts:
    build:
      context: ./${PATH_OMS_DISCOUNTS}/..
      dockerfile: ./docker/oms-discounts/Dockerfile
    image: aegee/oms-discounts:dev
    command: sh -c "sh /usr/app/scripts/bootstrap.sh && nodemon -e 'js,json' lib/run.js | bunyan"
    volumes:
      - /usr/app/src/node_modules
      - ./${PATH_OMS_DISCOUNTS}/../:/usr/app/src
    command: "sh -c '/usr/app/scripts/bootstrap.sh && npm run nodemon-start'"
