version: "3.4"

services:
  oms-discounts:
    build:
      context: ./${PATH_OMS_DISCOUNTS}/..
      dockerfile: ./docker/oms-discounts/Dockerfile.dev
    image: aegee/oms-discounts:dev
    volumes:
      - /usr/app/src/node_modules
      - ./${PATH_OMS_DISCOUNTS}/../:/usr/app/src
    command: "sh -c '/usr/app/scripts/bootstrap.sh && npm run nodemon-start'"
